# -*- coding: utf-8 -*-
"""Copy of KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZesfcnOkTfiSCGT5QPp92Nr8-ykKfV3
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# 20% training, 80% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=0.2, random_state=42
)

# KNN model
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

# Prediction
y_pred = knn.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# 20% training, 80% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=0.2, random_state=42
)

# Euclidean distance
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

# KNN implementation
def knn_predict(X_train, y_train, X_test, k):
    predictions = []

    for test_point in X_test:
        distances = []

        for i in range(len(X_train)):
            dist = euclidean_distance(test_point, X_train[i])
            distances.append((dist, y_train[i]))

        distances.sort(key=lambda x: x[0])
        k_labels = [label for _, label in distances[:k]]

        prediction = max(set(k_labels), key=k_labels.count)
        predictions.append(prediction)

    return np.array(predictions)

# Predict
k = 5
y_pred = knn_predict(X_train, y_train, X_test, k)

# Accuracy
accuracy = np.sum(y_pred == y_test) / len(y_test)
print("Accuracy:", accuracy)